### ISSUE TITLE
🐛 Bug Report: OpenAPI spec versioning against the product

### ISSUE THREAD

**Issue by toddb** [notifirehq/notifire#8217]
### 📜 Description

The OpenAPI specification for the **Novu API** incorrectly has the `version` field set to `'1.0'`, instead of reflecting the actual product version, which is currently `2.1.1`.

### Impact
* Documentation mismatch: Consumers may incorrectly assume they are integrating with version 1.0, not 2.1.1.
* Client confusion: Version misalignment makes it harder for users to trust the API documentation.
* Automation problems: Tools that generate client SDKs or validate API contracts based on the spec may be affected.

### 👟 Reproduction steps

1 . `wget https://api.novu.co/openapi.yaml`
Steps to Reproduce
	1.	Open the OpenAPI spec file `wget https://api.novu.co/openapi.yaml`
	2.	Locate the info section at the top of the file.
	3.	Observe that the version field is set to 1.0.

### Expected Behavior

The version field under the info section should reflect the current product version (2.1.1), ensuring consistency between the API documentation and the deployed product version.

### 👍 Expected behavior

```yaml
info:
  title: Novu API
  description: >-
    Novu REST API. Please see https://docs.novu.co/api-reference for more
    details.
  version: '2.1.1'
  contact:
    name: Novu Support
    url: https://discord.gg/novu
    email: support@novu.co
  termsOfService: https://novu.co/terms
  license:
    name: MIT
    url: https://opensource.org/license/mit
```

### 👎 Actual Behavior with Screenshots

```yaml
info:
  title: Novu API
  description: >-
    Novu REST API. Please see https://docs.novu.co/api-reference for more
    details.
  version: '1.0'
  contact:
    name: Novu Support
    url: https://discord.gg/novu
    email: support@novu.co
  termsOfService: https://novu.co/terms
  license:
    name: MIT
    url: https://opensource.org/license/mit
```

### Novu version

All version

### npm version

NA

### node version

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None
