### ISSUE TITLE
🐛 Bug Report: [docker] failed to register layer

### ISSUE THREAD

**Issue by y-nk** [notifirehq/notifire#8583]
### 📜 Description

with a docker compose (roughly) equal to:

```
include:
  - databases.yaml

services:
  novu-api:
    image: ghcr.io/novuhq/novu/api:2.3.0
    environment:
      # basics
      API_ROOT_URL: http://localhost:7001
      NOVU_SECRET_KEY: xxx
      # mongo
      MONGO_URL: mongodb://mongo:27017/novu?directConnection=true
      MONGO_AUTO_CREATE_INDEXES: true
      # redis
      REDIS_HOST: redis
      REDIS_CACHE_SERVICE_HOST: redis
      # s3
      S3_LOCAL_STACK: minio:9000
      S3_BUCKET_NAME: novu-local
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: password
      STORE_ENCRYPTION_KEY: xxx
      # frontend
      FRONT_BASE_URL: http://localhost:7000
      JWT_SECRET: xxx
      # config
      IS_API_IDEMPOTENCY_ENABLED: true
      IS_V2_ENABLED: true
    ports:
      - 7001:3000
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  novu-worker:
    image: ghcr.io/novuhq/novu/worker:2.3.0
    environment:
      # basics
      API_ROOT_URL: http://localhost:7001
      # mongo
      MONGO_URL: mongodb://mongo:27017/novu?directConnection=true
      MONGO_AUTO_CREATE_INDEXES: true
      # redis
      REDIS_HOST: redis
      REDIS_CACHE_SERVICE_HOST: redis
      # s3
      S3_LOCAL_STACK: minio:9000
      S3_BUCKET_NAME: novu-local
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: password
      STORE_ENCRYPTION_KEY: xxx
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  novu-ws:
    image: ghcr.io/novuhq/novu/ws:2.3.0
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo:27017/novu?directConnection=true
      REDIS_HOST: redis
      JWT_SECRET: xxx
    ports:
      - 7002:3000
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  novu-dashboard:
    image: ghcr.io/novuhq/novu/dashboard:2.3.0
    environment:
      VITE_SELF_HOSTED: true
      VITE_API_HOSTNAME: http://localhost:7001
      VITE_WEBSOCKET_HOSTNAME: http://localhost:7002
    ports:
      - 7000:4000
    depends_on:
      - novu-api
      - novu-worker
```

when calling `docker compose up` it never succeeds. i always get a:

```
failed to register layer: rename /var/lib/docker/image/overlay2/layerdb/tmp/write-set-890245166 /var/lib/docker/image/overlay2/layerdb/sha256/306422c3ef509d15b8593e7ebc8f65054141db5560fd9cc56ef839b41cfb3a57: file exists
```

### 👟 Reproduction steps

1. build a minimal docker compose
2. `docker compose up`

### 👍 Expected behavior

boot the stack

### 👎 Actual Behavior with Screenshots

crashes at pull

### Novu version

2.3.0

### 📃 Provide any additional context for the Bug.

running docker compose 2.36

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
